name: Build for WindowsCE

on:
  push:
    branches: "*"
    tags: '*'
  pull_request:
    branches: "*"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install CeGCC
      run: |
        wget https://github.com/brain-hackers/cegcc-build/releases/download/2022-10-26-225811/cegcc-x86_64-2022-10-26-225811.zip -O cegcc.zip
        unzip cegcc.zip -d /opt 

    - name: Download Tcl/Tk
      run: wget https://master.dl.sourceforge.net/project/tcltkce/tcltkce/8.4.6/tcltk846ce-arm.zip?viasf=1 -O tcltk.zip

    - name: Extract Tcl/Tk
      run: |
        unzip tcltk.zip
        mv tcltk846ce-arm/bin/*.dll .
    
    - name: Build
      run: |
        export PATH=$PATH:/opt/cegcc/bin
        export TOOL_PREFIX=/opt/cegcc/bin/arm-mingw32ce
        ./ce_build.sh

    - name: Pack
      run: ./ce_pack.sh

    - name: Upload log
      uses: actions/upload-artifact@v4
      with:
        name: log
        path: make.log

    - name: Upload zip file
      uses: actions/upload-artifact@v4
      with:
        name: cpython-wince
        path: wince_build
